Traceback (most recent call last):
  File "/scratch/users/u01tu20/EvalProject/GroupPr/gemma2.py", line 1, in <module>
    import pandas as pd
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 68, in <module>
    from pandas.core.frame import DataFrame
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/frame.py", line 149, in <module>
    from pandas.core.generic import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/generic.py", line 193, in <module>
    from pandas.core.window import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/u01tu20/sharedscratch/.conda/envs/EvalAlphaEnv/lib/python3.11/site-packages/pandas/_libs/window/aggregations.cpython-311-x86_64-linux-gnu.so)
srun: error: gpu01: task 0: Exited with exit code 1
